---

- hosts: all
  become: true
  pre_tasks:

  - name: Install Updates on (RedHat)
    tags: always
    dnf:
      update_cache: yes
    when: ansible_distribution in ["RedHat"]

  - name: Install Updates (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    when: ansible_distribution in ["Ubuntu"]


- hosts: web_servers
  become: true
  tasks: 

  - name: Install Nginx on (Ubuntu)
    apt:
      name: 
        - nginx
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Ubuntu"]

  - name: Custom Index Page
    copy:
      dest: /var/www/html/index.nginx-debian.html
      content: "Welcome Mohamed Alaa"

  # - name: Install Nginx on (Ubuntu 	)
  #   tags: apache,apache2,ubuntu
  #   apt:
  #     name:
  #       - apache2
  #     state: latest
  #     update_cache: yes
  #   when: ansible_distribution in ["RedHat"]
